// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0MjyzZp3DN7GxPLyXL5RBz3cVN4OK7nA',
    appId: '1:1003236991318:web:70926669d4619a8a1276f7',
    messagingSenderId: '1003236991318',
    projectId: 'podcastnotesapp',
    authDomain: 'podcastnotesapp.firebaseapp.com',
    storageBucket: 'podcastnotesapp.firebasestorage.app',
    measurementId: 'G-TVDDBZPM7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz6mltxcwW0s8SZBCliV-h-caGXwv8QzE',
    appId: '1:1003236991318:android:4c109df9ce73271c1276f7',
    messagingSenderId: '1003236991318',
    projectId: 'podcastnotesapp',
    storageBucket: 'podcastnotesapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZKSAzNMjWKlFyPnZUJwpX1Q-g40QHEA',
    appId: '1:1003236991318:ios:c3622cb355461b8b1276f7',
    messagingSenderId: '1003236991318',
    projectId: 'podcastnotesapp',
    storageBucket: 'podcastnotesapp.firebasestorage.app',
    iosBundleId: 'com.example.podcastNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZKSAzNMjWKlFyPnZUJwpX1Q-g40QHEA',
    appId: '1:1003236991318:ios:c3622cb355461b8b1276f7',
    messagingSenderId: '1003236991318',
    projectId: 'podcastnotesapp',
    storageBucket: 'podcastnotesapp.firebasestorage.app',
    iosBundleId: 'com.example.podcastNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0MjyzZp3DN7GxPLyXL5RBz3cVN4OK7nA',
    appId: '1:1003236991318:web:6127bad0c64fe0191276f7',
    messagingSenderId: '1003236991318',
    projectId: 'podcastnotesapp',
    authDomain: 'podcastnotesapp.firebaseapp.com',
    storageBucket: 'podcastnotesapp.firebasestorage.app',
    measurementId: 'G-D9DPH966YN',
  );
}
